server {
    listen 80;
    server_name *.dwijacode.my.id;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy untuk mengarahkan request API ke backend-proxy
    location /api-backend/ {
        proxy_pass http://backend-proxy:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}