FROM python:3.9-alpine

# Install curl dan dependencies dengan apk
RUN apk add --no-cache \
    curl \
    gcc \
    musl-dev \
    libffi-dev \
    jq \
    tzdata

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .

EXPOSE 8001
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001"]